name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/login.cy.js
            cypress/e2e/register.cy.js
            cypress/e2e/search.cy.js